version: '3'

services:
  build:
    build: .
    container_name: news
    restart: unless-stopped
    ports:
      - '4000:8070'
    depends_on:
      - postgres
    volumes:
      - '/root/news-public-data:/usr/src/news-nodejs/build/public'

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: news
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data

